[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "etch"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
evaluator = { path = "../evaluator" }
graph_render = { path = "../graph_render" }
kicad = { path = "../kicad" }
pcb = { path = "../pcb" }
schematic = { path = "../schematic" }
