[package]
name = "etch_lsp"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "etch-lsp"
path = "src/main.rs"

[dependencies]
highlighting = { path = "../highlighting" }
parser = { path = "../parser" }
tokio = { version = "1", features = ["io-std", "macros", "rt-multi-thread"] }
tower-lsp = "0.20"
